### ISSUE TITLE
Failed to setup database when running `pushkin init site`

### ISSUE THREAD

**Issue by rui-han** [hrcn/pushkin-cli#2]
Error: connect ECONNREFUSED 127.0.0.1:5432

**Comment by rui-han** [comment]
This environment variable is required for you to use the PostgreSQL image. It must not be empty or undefined. This environment variable sets the superuser password for PostgreSQL. The default superuser is defined by the POSTGRES_USER environment variable: https://hub.docker.com/_/postgres

Add an environment variable to the test_db in `docker-compose.dev.yml` in `./pushkin`:
```yaml
test_db:
    image: 'postgres:11'
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
    volumes:
      - 'test_db_volume:/var/lib/postgresql/data'
```

Then set the password in `pushkin.yaml` for authentication:
```yaml
databases:
  localtestdb:
    user: 'postgres'
    pass: 'example'
    url: 'localhost'
    name: 'test_db'
```
